## Actividad 3_11

<div style="border-style:groove;border-width:thin;padding:10px">

Trabajamos en una empresa de alquiler de bicicletas en Seul. El departamento de mantenimiento de bicicletas ha pedido a nuestro departamento de DataScience si es posible poder saber, a priori, cuantas bicicletas tiene que haber disponibles porque ellos tienen que ir retirando bicicletas para repararlas. Tenemos los datos que se muestran a continuación. ¿Será posible saber cuantas tienen que tener en circulación?

</div>

In [135]:
import pandas as pd
bicicletas = pd.read_csv("SeoulBikeData.csv", sep=',',encoding='latin-1')
bicicletas.head()

,Date,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Seasons,Holiday,Functioning Day
0,01/12/2017,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
1,01/12/2017,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
2,01/12/2017,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,Winter,No Holiday,Yes
3,01/12/2017,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,Winter,No Holiday,Yes
4,01/12/2017,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,Winter,No Holiday,Yes

In [136]:

bicicletas['Date'] = pd.to_datetime(bicicletas['Date'],dayfirst=True)

In [137]:
import datetime
bicicletas['Date'] = bicicletas['Date'].apply(datetime.datetime.weekday)

In [138]:
bicicletas.replace('Holiday',1,inplace=True)
bicicletas.replace('No Holiday',0,inplace=True)

C:\Users\Equipo\AppData\Local\Temp\ipykernel_27928\2390910612.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bicicletas.replace('No Holiday',0,inplace=True)

In [139]:
bicicletas.replace('Yes',1,inplace=True)
bicicletas.replace('No',0,inplace=True)

C:\Users\Equipo\AppData\Local\Temp\ipykernel_27928\3092876951.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  bicicletas.replace('No',0,inplace=True)

In [140]:
bicicletas = pd.get_dummies(bicicletas,dtype=int)

In [141]:
bicicletas.head()

,Date,Rented Bike Count,Hour,Temperature(°C),Humidity(%),Wind speed (m/s),Visibility (10m),Dew point temperature(°C),Solar Radiation (MJ/m2),Rainfall(mm),Snowfall (cm),Holiday,Functioning Day,Seasons_Autumn,Seasons_Spring,Seasons_Summer,Seasons_Winter
0,4,254,0,-5.2,37,2.2,2000,-17.6,0.0,0.0,0.0,0,1,0,0,0,1
1,4,204,1,-5.5,38,0.8,2000,-17.6,0.0,0.0,0.0,0,1,0,0,0,1
2,4,173,2,-6.0,39,1.0,2000,-17.7,0.0,0.0,0.0,0,1,0,0,0,1
3,4,107,3,-6.2,40,0.9,2000,-17.6,0.0,0.0,0.0,0,1,0,0,0,1
4,4,78,4,-6.0,36,2.3,2000,-18.6,0.0,0.0,0.0,0,1,0,0,0,1

In [142]:
bicicletas.corr()['Rented Bike Count'].abs().sort_values(ascending=False)[1:]

Temperature(°C)              0.538558
Seasons_Winter               0.424925
Hour                         0.410257
Dew point temperature(°C)    0.379788
Seasons_Summer               0.296549
Solar Radiation (MJ/m2)      0.261837
Functioning Day              0.203943
Humidity(%)                  0.199780
Visibility (10m)             0.199280
Snowfall (cm)                0.141804
Rainfall(mm)                 0.123074
Wind speed (m/s)             0.121108
Seasons_Autumn               0.102753
Holiday                      0.072338
Date                         0.029357
Seasons_Spring               0.022888
Name: Rented Bike Count, dtype: float64

In [143]:
bicicletas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 0 to 8759
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Date                       8760 non-null   int64
 1   Rented Bike Count          8760 non-null   int64
 2   Hour                       8760 non-null   int64
 3   Temperature(°C)            8760 non-null   float64
 4   Humidity(%)                8760 non-null   int64
 5   Wind speed (m/s)           8760 non-null   float64
 6   Visibility (10m)           8760 non-null   int64
 7   Dew point temperature(°C)  8760 non-null   float64
 8   Solar Radiation (MJ/m2)    8760 non-null   float64
 9   Rainfall(mm)               8760 non-null   float64
 10  Snowfall (cm)              8760 non-null   float64
 11  Holiday                    8760 non-null   int64
 12  Functioning Day            8760 non-null   int64
 13  Seasons_Autumn             8760 non-null   int64
 14  Seasons_Spring             8760 non-null   int64
 15  Seasons_Summer             8760 non-null   int64
 16  Seasons_Winter             8760 non-null   int64
dtypes: float64(6), int64(11)
memory usage: 1.1 MB

In [144]:
X = bicicletas.drop(['Rented Bike Count'],axis=1)
y = bicicletas['Rented Bike Count'].to_frame()

In [145]:
from sklearn.preprocessing import StandardScaler
escalador = StandardScaler()
X = escalador.fit_transform(X)

In [146]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [147]:
X.shape

(8760, 16)

In [148]:
from sklearn.tree import DecisionTreeRegressor
#tree_reg = DecisionTreeRegressor(max_depth=8,min_samples_leaf=10,min_samples_split=25,max_leaf_nodes=100,random_state=42)
tree_reg = DecisionTreeRegressor(max_depth=9, min_samples_split=20, min_samples_leaf=2,random_state=42)
tree_reg.fit(X_train, y_train)

DecisionTreeRegressor(max_depth=9, min_samples_leaf=2, min_samples_split=20,
                      random_state=42)

In [149]:
y_pred = tree_reg.predict(X_test)
from sklearn.metrics import r2_score
r2_score(y_test,y_pred)

0.8238891744028065

In [150]:
from sklearn.svm import SVR
regresor = SVR(kernel='rbf',C=10000)
regresor.fit(X_train,y_train)
y_pred = regresor.predict(X_test)
r2_score(y_test,y_pred)

c:\Users\Equipo\anaconda3\Lib\site-packages\sklearn\utils\validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.8130668798133128