# Métodos para el cálculo de distancias

Todos los métodos de clustering necesitan definir y cuantificar la similitud entre las observaciones, para ello se utiliza el concepto de **distancia**.

En este notebook vamos a ver diferentes métodos para el cálculo de distancias.

## Distancia euclídea

La distancia euclídea entre dos puntos se define como la longitud del segmento que los une.
<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/6/67/Distance_Formula.svg/1200px-Distance_Formula.svg.png" width="700">

Este cálculo se puede ampliar a n dimensiones.

En clustering es común utilizar la distancia eucídea al cuadrado para asignar mayor peso a los datos alejados.

## Distancia de Manhattan

Se define la distancia entre dos puntos  p  y  q  como el sumatorio de las diferencias absolutas entre cada dimensión. Esta medida se ve menos afectada por outliers (es más robusta) que la distancia euclídea debido a que no eleva al cuadrado las diferencias.

Comparación entre la distancia euclídea (verde) y la distancia de manhattan (segmento rojo, amarillo y azul) en un espacio bidimensional. Existen múltiples caminos para unir dos puntos con una misma distancia de manhattan, pero solo uno con la distancia euclídea.

<img src="https://upload.wikimedia.org/wikipedia/commons/thumb/0/08/Manhattan_distance.svg/1200px-Manhattan_distance.svg.png" width="500">

## Correlación

La correlación determina la distancia entre dos muestras teniendo en cuenta patrones en lugar del desplazamiento de una magnitud.

Ejemplo: obs_1 y obs_2 tienen el mismo patrón, pero obs_2 está desplazada por debajo de obs_1. obs_3 tiene un patrón distinto a las demás, pero su rango de valores es similar al de obs_2. Acorde a la distancia euclídea, las observaciones obs_2 y obs_3 son las más similares ya que la suma de la distancia al cuadrado entre sus valores es menor. Sin embargo, **acorde a la correlación de Pearson, las observaciones más similares son obs_1 y obs_2 ya que siguen el mismo patrón**.

<img src="https://bradleyboehmke.github.io/HOML/18-kmeans_files/figure-html/correlation-distance-example-1.png" width="700">

# Cálculo de distancias en Aprendizaje No Supervisado

En aprendizaje no supervisado, los algoritmos trabajan sin etiquetas.  
Por eso, medir la **similitud o diferencia entre datos** es fundamental.

Las métricas más utilizadas son:

- **Distancia euclídea**: distancia "en línea recta"
- **Distancia Manhattan**: suma de diferencias absolutas
- **Distancia Minkowski**: generalización que incluye las dos anteriores
Estas distancias se utilizan en algoritmos como **K-Means** o **clustering jerárquico**.

In [1]:
# IMportación de Librerías
import pandas as pd
from sklearn.metrics import pairwise_distances
from sklearn.preprocessing import scale

In [2]:
# Carga de Datos
# Dataset USArrests
url = "https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/USArrests.csv"
datos = pd.read_csv(url, index_col=0)

datos.head()

            Murder  Assault  UrbanPop  Rape
rownames
Alabama       13.2      236        58  21.2
Alaska        10.0      263        48  44.5
Arizona        8.1      294        80  31.0
Arkansas       8.8      190        50  19.5
California     9.0      276        91  40.6

## Escalado de Datos

In [3]:
# Escalado (muy importante en clustering)
datos_scaled = scale(datos)

# Convertimos a DataFrame para mantener nombres
datos_scaled = pd.DataFrame(datos_scaled, index=datos.index, columns=datos.columns)

datos_scaled.head()

              Murder   Assault  UrbanPop      Rape
rownames
Alabama     1.255179  0.790787 -0.526195 -0.003451
Alaska      0.513019  1.118060 -1.224067  2.509424
Arizona     0.072361  1.493817  1.009122  1.053466
Arkansas    0.234708  0.233212 -1.084492 -0.186794
California  0.281093  1.275635  1.776781  2.088814

## Distancia Euclídea

In [4]:
dist_euclidea = pairwise_distances(datos_scaled, metric='euclidean')

dist_euclidea = pd.DataFrame(dist_euclidea, index=datos.index, columns=datos.index)

dist_euclidea.head()

rownames,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,Florida,Georgia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
rownames,,,,,,,,,,,,,,,,,,,,,
Alabama,0.000000,2.731204,2.316805,1.302905,3.296239,2.677982,3.247941,2.039794,2.321467,1.142922,...,3.114865,0.849285,1.663037,3.121978,4.019551,1.501060,2.675068,3.156067,3.540315,1.847673
Alaska,2.731204,0.000000,2.728061,2.854730,3.043126,2.350139,4.788035,3.658129,3.027189,2.848063,...,4.289835,2.359973,3.184799,3.988171,4.920238,3.080165,3.304740,4.546147,4.920609,3.534873
Arizona,2.316805,2.728061,0.000000,2.745350,1.323789,1.378889,3.295984,1.928755,1.767154,2.815493,...,4.143656,2.322325,1.661557,2.550073,5.152148,2.334114,2.161637,4.543079,3.982614,2.719636
Arkansas,1.302905,2.854730,2.745350,0.000000,3.801851,2.859794,2.634114,1.818602,3.406433,2.234216,...,1.891493,1.439921,2.374419,2.631433,2.772160,1.007227,2.152979,2.015425,2.636746,1.001328
California,3.296239,3.043126,1.323789,3.801851,0.000000,1.300691,4.107674,3.104992,2.045563,3.412354,...,5.104215,3.042505,2.191845,3.101336,6.093594,3.248623,2.802842,5.544077,4.783573,3.762087

## Distancia Manhattan

In [5]:
dist_manhattan = pairwise_distances(datos_scaled, metric='manhattan')

dist_manhattan = pd.DataFrame(dist_manhattan, index=datos.index, columns=datos.index)

dist_manhattan.head()

rownames,Alabama,Alaska,Arizona,Arkansas,California,Colorado,Connecticut,Delaware,Florida,Georgia,...,South Dakota,Tennessee,Texas,Utah,Vermont,Virginia,Washington,West Virginia,Wisconsin,Wyoming
rownames,,,,,,,,,,,,,,,,,,,,,
Alabama,0.000000,4.280180,4.478083,2.319686,5.854175,4.900178,6.238559,3.276700,4.399533,1.912794,...,5.811439,1.266342,2.539272,5.443972,7.722916,2.462605,4.822792,6.227581,6.356511,3.136939
Alaska,4.280180,0.000000,4.505562,3.998950,3.810958,3.921331,9.034417,6.024073,5.717205,5.200766,...,7.211555,4.317047,5.660027,7.873144,9.123032,5.258463,6.540163,7.627696,9.152369,5.932797
Arizona,4.478083,4.505562,0.000000,4.756827,2.229921,2.107303,5.699093,3.386620,2.287087,5.119521,...,7.923885,4.375376,2.787296,4.119097,9.835362,4.062719,3.763136,8.340027,7.352362,4.970236
Arkansas,2.319686,3.998950,4.756827,0.000000,6.225690,4.403165,5.035467,3.188758,6.719219,3.626421,...,3.491753,2.470878,3.778548,4.607566,5.403230,1.518350,3.986386,3.907895,5.153419,1.933847
California,5.854175,3.810958,2.229921,6.225690,0.000000,2.239990,7.492650,5.180178,3.905415,6.495613,...,9.717443,5.751468,4.163388,5.912655,11.628920,5.670737,5.556694,10.133584,9.145920,6.763793

## Búsqueda de estados similares

In [10]:
# Nos quedamos con la mitad de la matriz (sin duplicados)
import numpy as np

indices = np.triu_indices(dist_euclidea.shape[0], k=1)


distancias = dist_euclidea.values[indices]

pares = list(zip(indices[0], indices[1], distancias))

pares_ordenados = sorted(pares, key=lambda x: x[2])

for i in range(5):
    a = datos.index[pares_ordenados[i][0]]
    b = datos.index[pares_ordenados[i][1]]
    d = pares_ordenados[i][2]
    print(f"{a} - {b}: {d:.2f}")

Iowa - New Hampshire: 0.21
Illinois - New York: 0.35
Indiana - Kansas: 0.43
Minnesota - Wisconsin: 0.50
Maine - New Hampshire: 0.50

## Búsqueda de estados menos similares

In [11]:
# Los más lejanos
for i in range(1,6):
    a = datos.index[pares_ordenados[-i][0]]
    b = datos.index[pares_ordenados[-i][1]]
    d = pares_ordenados[-i][2]
    print(f"{a} - {b}: {d:.2f}")

Florida - Vermont: 6.14
Nevada - North Dakota: 6.11
Nevada - Vermont: 6.11
Florida - North Dakota: 6.10
California - Vermont: 6.09

## Cuestiones

1. ¿Qué estados son más parecidos? ¿Por qué crees que ocurre?
    -   Porque las caractersticas de cada uno son mas similires. Ocurre porque tienen valores muy similares en las cuatro variables 
        (asesinatos, asaltos, población urbana y   violaciones), es decir, sus perfiles de criminalidad son casi idénticos una vez escalados los datos.

2. ¿Qué estados son más diferentes?
    -   Basandonos en las caracteristicas de cada uno, podemos ver que si que al contrario que en los mas parecidos que tienen caracteristicas mas
        similares, aqui ocurre lo contrario, son muy distintas.

3. ¿Por qué es necesario escalar los datos antes de calcular distancias?
    -   Es necesario porque tenemos que igualar los datos dentro de un rango para que las distancias sean similares y "pesen" lo mismo.

4. ¿Para qué algoritmos sería útil este cálculo de distancias?
    -   Por ejemplo para cuando usemos kmeans ya que se basa en las distancias de los valores para agruparlos por clusters, entonces seria
        necesario el escalado.