# Actividad 2_9: 

Vamos a hacer un trabajo en grupos. Dividiros en grupos de 2 o 3 personas (organizaros el trabajo para que se pueda hacer en paralelo). Debéis responder a la siguiente pregunta. ¿Existe relación entre la emisión de CO2 que tienen los países y su esperanza de vida? Para ello os sugiero lo siguiente:


1. Podéis buscar los datasets necesarios en el portal Kaggle.
2. Una vez encontrados hay que importar los datos y tratarlos con el objetivo de solucionar la pregunta realizada.
3. Puedes normalizar, pintar gráficas, buscar índices calculados en base a los datos, etc.
4. También puedes utilizar la matriz de correlación. La veremos con detalle más adelante, pero aquí tienes como usarla en Pandas: https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.corr.html

In [3]:
# Código
import pandas as pd

df = pd.read_csv("gapminder_data_graphs.csv")
df.head(100)

,country,continent,year,life_exp,hdi_index,co2_consump,gdp,services
0,Afghanistan,Asia,1998,53.3,0.344,0.0522,NaN,24.4
1,Afghanistan,Asia,1999,54.7,0.348,0.0402,NaN,24.6
2,Afghanistan,Asia,2000,54.7,0.350,0.0370,NaN,24.7
3,Afghanistan,Asia,2001,54.8,0.353,0.0376,NaN,24.7
4,Afghanistan,Asia,2002,55.5,0.384,0.0471,333.0,25.6
...,...,...,...,...,...,...,...,...
95,Argentina,South America,2009,75.8,0.821,4.4200,12400.0,75.6
96,Argentina,South America,2010,75.9,0.829,4.5700,13600.0,75.4
97,Argentina,South America,2011,76.0,0.835,4.6100,14200.0,75.4
98,Argentina,South America,2012,76.2,0.834,4.6000,13900.0,75.7
99,Argentina,South America,2013,76.3,0.835,4.5600,14100.0,75.4

In [12]:
country = []
life_exp = []
co2 = []
year = []

df_filtrado = df.loc[(df["year"] == 2018)]
df_filtrado.head(100)

country = df_filtrado["country"].to_list()
life_exp = df_filtrado["life_exp"].to_list()
co2 = df_filtrado["co2_consump"].to_list()
year = df_filtrado["year"].to_list()

In [13]:
df_completo = pd.DataFrame( {
    "Country" : country,
    "Life exp" : life_exp,
    "CO2 consump" : co2,
    "Year" : year
    })
df_completo.head(100)

        Country  Life exp  CO2 consump  Year
0   Afghanistan      62.7       0.2540  2018
1       Albania      78.4       1.5900  2018
2       Algeria      76.0       3.6900  2018
3        Angola      64.6       1.1200  2018
4     Argentina      76.5       4.4100  2018
..          ...       ...          ...   ...
95       Malawi      64.1       0.0762  2018
96     Malaysia      75.2       8.0800  2018
97     Maldives      79.0       2.9600  2018
98         Mali      61.2       0.1870  2018
99        Malta      82.5       3.6100  2018

[100 rows x 4 columns]