In [71]:
import pandas as pd
pegatinas = pd.read_csv('stickers.csv')
pegatinas.head()

,id,date,country,city,store,product,num_sold
0,0,2010-01-01,Canada,Otawa,Discount Stickers,Holographic Goose,NaN
1,1,2010-01-01,Canada,Toronto,Discount Stickers,Kaggle,973.0
2,2,2010-01-01,Canada,Toronto,Discount Stickers,Kaggle Tiers,906.0
3,3,2010-01-01,Canada,Otawa,Discount Stickers,Kerneler,423.0
4,4,2010-01-01,Canada,Otawa,Discount Stickers,Kerneler Dark Mode,491.0

In [72]:
#Separa los años y meses en columnas categóricas. 
#Elimina las columnas que debes eliminar
#Prepara los datos para poder lanzar los algoritmos de machine learning.
#Las 10 variables con más correlación con num_sold.
#Prueba con SVM y con DecissionTree.

#1
years = []
months = []
for i,row in pegatinas.iterrows():
    years.append(row['date'].split('-')[0])
    months.append(row['date'].split('-')[1])
pegatinas['year'] = years
pegatinas['month'] = months

pegatinas.head()

,id,date,country,city,store,product,num_sold,year,month
0,0,2010-01-01,Canada,Otawa,Discount Stickers,Holographic Goose,NaN,2010,01
1,1,2010-01-01,Canada,Toronto,Discount Stickers,Kaggle,973.0,2010,01
2,2,2010-01-01,Canada,Toronto,Discount Stickers,Kaggle Tiers,906.0,2010,01
3,3,2010-01-01,Canada,Otawa,Discount Stickers,Kerneler,423.0,2010,01
4,4,2010-01-01,Canada,Otawa,Discount Stickers,Kerneler Dark Mode,491.0,2010,01

In [73]:
pegatinas.shape

(22112, 9)

In [74]:
pegatinas.drop(['id','date','city'],axis=1,inplace=True)
pegatinas.head()

  country              store             product  num_sold  year month
0  Canada  Discount Stickers   Holographic Goose       NaN  2010    01
1  Canada  Discount Stickers              Kaggle     973.0  2010    01
2  Canada  Discount Stickers        Kaggle Tiers     906.0  2010    01
3  Canada  Discount Stickers            Kerneler     423.0  2010    01
4  Canada  Discount Stickers  Kerneler Dark Mode     491.0  2010    01

In [75]:
pegatinas.head()

  country              store             product  num_sold  year month
0  Canada  Discount Stickers   Holographic Goose       NaN  2010    01
1  Canada  Discount Stickers              Kaggle     973.0  2010    01
2  Canada  Discount Stickers        Kaggle Tiers     906.0  2010    01
3  Canada  Discount Stickers            Kerneler     423.0  2010    01
4  Canada  Discount Stickers  Kerneler Dark Mode     491.0  2010    01

In [76]:
pegatinas.dropna(inplace=True)

In [77]:
pegatinas.info()

<class 'pandas.core.frame.DataFrame'>
Index: 20863 entries, 1 to 22111
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   country   20863 non-null  object
 1   store     20863 non-null  object
 2   product   20863 non-null  object
 3   num_sold  20863 non-null  float64
 4   year      20863 non-null  object
 5   month     20863 non-null  object
dtypes: float64(1), object(5)
memory usage: 1.1+ MB

In [78]:
pegatinas = pd.get_dummies(pegatinas,columns=['country','store','product','year','month'],dtype='int')
pegatinas.head()

,num_sold,country_Canada,country_Finland,country_Italy,country_Kenya,country_Norway,country_Singapore,store_Discount Stickers,store_Premium Sticker Mart,store_Stickers for Less,...,year_2010,month_01,month_02,month_03,month_04,month_05,month_06,month_07,month_08,month_09
1,973.0,1,0,0,0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
2,906.0,1,0,0,0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
3,423.0,1,0,0,0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
4,491.0,1,0,0,0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
5,300.0,1,0,0,0,0,0,0,0,1,...,1,1,0,0,0,0,0,0,0,0

In [79]:
pegatinas.columns

Index(['num_sold', 'country_Canada', 'country_Finland', 'country_Italy',
       'country_Kenya', 'country_Norway', 'country_Singapore',
       'store_Discount Stickers', 'store_Premium Sticker Mart',
       'store_Stickers for Less', 'product_Holographic Goose',
       'product_Kaggle', 'product_Kaggle Tiers', 'product_Kerneler',
       'product_Kerneler Dark Mode', 'year_2010', 'month_01', 'month_02',
       'month_03', 'month_04', 'month_05', 'month_06', 'month_07', 'month_08',
       'month_09'],
      dtype='object')

In [80]:
pegatinas.corr()['num_sold'].abs().sort_values(ascending=False)[1:10]

country_Norway                0.460731
country_Kenya                 0.446813
product_Holographic Goose     0.352147
store_Discount Stickers       0.345647
product_Kaggle                0.325052
store_Premium Sticker Mart    0.246098
product_Kaggle Tiers          0.215778
product_Kerneler              0.179344
country_Italy                 0.120508
Name: num_sold, dtype: float64

In [81]:
X = pegatinas.drop(['num_sold'],axis=1)
y = pegatinas['num_sold'].to_frame()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [ ]:
#APARTADO 2
from sklearn.svm import SVR
svr_rbf = SVR(kernel="rbf", C=60)
#svr_lnr = SVR(kernel="linear", C=60)
#svr_poly = SVR(kernel="poly", degree=1, C=60)
svr_rbf.fit(X_train,y_train)
y_pred_rbf = svr_rbf.predict(X_test)
#svr_lnr.fit(X_train,y_train)
#y_pred_lnr = svr_lnr.predict(X_test)
#svr_poly.fit(X_train,y_train)
#y_pred_poly = svr_poly.predict(X_test)
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred_rbf))
#print(r2_score(y_test, y_pred_lnr))
#print(r2_score(y_test, y_pred_poly))

/home/loren/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [82]:
#APARTADO 3
from sklearn.tree import DecisionTreeRegressor
#tree_reg = DecisionTreeRegressor(random_state=0,max_depth=9,min_samples_split=15)
tree_reg = DecisionTreeRegressor(random_state=0)
tree_reg.fit(X_train, y_train)
y_pred_tree = tree_reg.predict(X_test)
from sklearn.metrics import r2_score
print(r2_score(y_test, y_pred_tree))

0.9738168209033045

In [83]:
pegatinas.head()

,num_sold,country_Canada,country_Finland,country_Italy,country_Kenya,country_Norway,country_Singapore,store_Discount Stickers,store_Premium Sticker Mart,store_Stickers for Less,...,year_2010,month_01,month_02,month_03,month_04,month_05,month_06,month_07,month_08,month_09
1,973.0,1,0,0,0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
2,906.0,1,0,0,0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
3,423.0,1,0,0,0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
4,491.0,1,0,0,0,0,0,1,0,0,...,1,1,0,0,0,0,0,0,0,0
5,300.0,1,0,0,0,0,0,0,0,1,...,1,1,0,0,0,0,0,0,0,0

In [85]:
X5 = pegatinas.iloc[[0]].drop(['num_sold'],axis=1)
print(X5)
X5 = scaler.transform(X5)

   country_Canada  country_Finland  country_Italy  country_Kenya  \
1               1                0              0              0

   country_Norway  country_Singapore  store_Discount Stickers  \
1               0                  0                        1

   store_Premium Sticker Mart  store_Stickers for Less  \
1                           0                        0

   product_Holographic Goose  ...  year_2010  month_01  month_02  month_03  \
1                          0  ...          1         1         0         0

   month_04  month_05  month_06  month_07  month_08  month_09
1         0         0         0         0         0         0

[1 rows x 24 columns]

In [86]:
tree_reg.predict(X5)

array([684.6])

# Ejercicio 2

In [87]:
#Importa setas_train1 y setas_train2
#Junta los dos datasets en uno solo.
#Elimina las columnas que tengas que eliminar.
#La columna class tiene que ser 0 1
#Prepara los datos para entrenar con un algoritmo de Machine Learning.
#Prueba con SVM y con DecissionTree. Tendrás problemas de tiempo.
#hacer un predict y alguna pregunta de teoría.
import pandas as pd
setas1 = pd.read_csv('setas1.csv')
setas2 = pd.read_csv('setas2.csv')

In [ ]:

setas = pd.merge(left=setas1,right=setas2,how='inner',left_on='id',right_on='reg')
#setas_pre = pd.merge(left=setas1,right=setas2,how='inner',left_on='id',right_on='reg')
print(setas.shape)
setas.dropna(inplace=True)
print(setas.shape)
setas.drop(['id','reg'],axis=1,inplace=True)
#setas = pd.get_dummies(setas,columns=['cap-shape', 'cap-surface', 'cap-color', 'does-bruise-or-bleed', 'gill-attachment', 'gill-color', 'stem-color', 'has-ring', 'ring-type', 'habitat', 'season'],dtype='int')
setas = pd.get_dummies(setas,columns=['cap-color',
       'does-bruise-or-bleed', 'has-ring', 'habitat',
       'season'],dtype='int')

##APARTADO 2
setas.replace({'e':0,'p':1},inplace=True)
setas.head()

(19999, 9)
(19998, 9)

,class,stem-height,cap-color_b,cap-color_e,cap-color_g,cap-color_i,cap-color_k,cap-color_l,cap-color_n,cap-color_o,...,habitat_n,habitat_p,habitat_s,habitat_u,habitat_w,habitat_y,season_a,season_s,season_u,season_w
0,0,4.51,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0
1,1,4.79,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,1
2,0,6.85,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
3,0,4.16,0,0,1,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,3.37,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,1,0,0,0

In [20]:
setas_pre.to_csv('setas.csv',index=False)

In [89]:
setas.corr()['class'].abs().sort_values(ascending=False)[1:20]

season_w                  0.125635
cap-color_e               0.125160
cap-color_b               0.115582
cap-color_r               0.108962
cap-color_n               0.104542
habitat_g                 0.098712
habitat_w                 0.089574
cap-color_o               0.085757
habitat_l                 0.077600
season_s                  0.077540
habitat_p                 0.067057
cap-color_g               0.059556
cap-color_y               0.059318
season_u                  0.057324
has-ring_t                0.054338
has-ring_f                0.054206
stem-height               0.051605
cap-color_p               0.051510
does-bruise-or-bleed_t    0.050600
Name: class, dtype: float64

In [90]:
X = setas.drop(['class'],axis=1)
y = setas['class'].to_frame()
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X = scaler.fit_transform(X)
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [107]:
#APARTADO 3
from sklearn.tree import DecisionTreeClassifier
tree_cla = DecisionTreeClassifier(random_state=0,max_depth=17,min_samples_split=50)
tree_cla.fit(X_train, y_train)
y_pred_tree = tree_cla.predict(X_test)
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred_tree))

0.7688

In [47]:
from sklearn.svm import SVC
svc_rbf = SVC(kernel="rbf", C=2000, coef0=1)
svc_rbf.fit(X_train,y_train)
y_pred_rbf = svc_rbf.predict(X_test)
print(accuracy_score(y_test, y_pred_rbf))

/home/loren/anaconda3/lib/python3.11/site-packages/sklearn/utils/validation.py:1184: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

0.7844

In [51]:
setas_nuevas = pd.read_csv('setas_nuevas.csv')

In [52]:
setas_nuevas.drop(['id','reg'],axis=1,inplace=True)
#setas = pd.get_dummies(setas,columns=['cap-shape', 'cap-surface', 'cap-color', 'does-bruise-or-bleed', 'gill-attachment', 'gill-color', 'stem-color', 'has-ring', 'ring-type', 'habitat', 'season'],dtype='int')
setas_nuevas = pd.get_dummies(setas_nuevas,columns=['cap-color',
       'does-bruise-or-bleed', 'has-ring', 'habitat',
       'season'],dtype='int')
setas_nuevas.replace({'e':0,'p':1},inplace=True)

In [57]:
print(X_test[0])

[-0.7052813  -0.13710841 -0.25865307  3.62945271 -0.0070716  -0.14213381
 -0.11228639 -0.8808312  -0.24541172 -0.17692705 -0.15598166 -0.1563177
 -0.37165215 -0.37443536  0.45708067 -0.45708067  0.5655314  -0.0070716
 -0.56545439 -0.0070716   0.65774168 -0.40984269 -0.20253469 -0.24160967
 -0.2279751  -0.0070716  -0.07368761 -0.0070716  -0.04476839 -0.08151391
 -0.0070716  -0.98422285  4.55119271 -0.76814408 -0.31603639]