In [5]:
import pandas as pd

titanic_train = pd.read_csv("train.csv")
titanic_test = pd.read_csv("test.csv")

titanic = pd.concat([titanic_train, titanic_test], ignore_index=True)

titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [6]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 122.8+ KB

In [7]:
titanic_filtrado = titanic.drop(columns=["PassengerId", "Name", "Cabin", "Ticket"])
titanic_filtrado.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       0.0       3    male  22.0      1      0   7.2500        S
1       1.0       1  female  38.0      1      0  71.2833        C
2       1.0       3  female  26.0      0      0   7.9250        S
3       1.0       1  female  35.0      1      0  53.1000        S
4       0.0       3    male  35.0      0      0   8.0500        S

In [8]:
titanic_filtrado.shape

(1309, 8)

In [10]:
titanic_filtrado = titanic_filtrado.dropna()
titanic_filtrado.shape

(712, 8)

In [19]:
titanic_filtrado["Embarked"].unique()

array(['S', 'C', 'Q'], dtype=object)

In [12]:
df_modelo = pd.get_dummies(titanic_filtrado, columns=["Sex", "Embarked"], dtype=int)
df_modelo.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0.0,3,22.0,1,0,7.2500,0,1,0,0,1
1,1.0,1,38.0,1,0,71.2833,1,0,1,0,0
2,1.0,3,26.0,0,0,7.9250,1,0,0,0,1
3,1.0,1,35.0,1,0,53.1000,1,0,0,0,1
4,0.0,3,35.0,0,0,8.0500,0,1,0,0,1

In [14]:
df_modelo.corr(numeric_only=True)["Survived"].abs().sort_values(ascending=False)[1:]

Sex_male      0.536762
Sex_female    0.536762
Pclass        0.356462
Fare          0.266100
Embarked_C    0.195673
Embarked_S    0.159015
Parch         0.095265
Age           0.082446
Embarked_Q    0.048966
SibSp         0.015523
Name: Survived, dtype: float64