In [45]:
from sklearn.datasets import make_moons
from sklearn.tree import DecisionTreeClassifier
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

from sklearn.tree import export_graphviz
from sklearn.datasets import make_circles
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [46]:
titanic_train = pd.read_csv("train.csv")
titanic_test = pd.read_csv("test.csv")

titanic = pd.concat([titanic_train, titanic_test], ignore_index=True)

titanic.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0.0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1.0,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1.0,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1.0,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0.0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [47]:
titanic.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1309 entries, 0 to 1308
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  1309 non-null   int64
 1   Survived     891 non-null    float64
 2   Pclass       1309 non-null   int64
 3   Name         1309 non-null   object
 4   Sex          1309 non-null   object
 5   Age          1046 non-null   float64
 6   SibSp        1309 non-null   int64
 7   Parch        1309 non-null   int64
 8   Ticket       1309 non-null   object
 9   Fare         1308 non-null   float64
 10  Cabin        295 non-null    object
 11  Embarked     1307 non-null   object
dtypes: float64(3), int64(4), object(5)
memory usage: 122.8+ KB

In [48]:
titanic_filtrado = titanic.drop(columns=["PassengerId", "Name", "Cabin", "Ticket"])
titanic_filtrado.head()

   Survived  Pclass     Sex   Age  SibSp  Parch     Fare Embarked
0       0.0       3    male  22.0      1      0   7.2500        S
1       1.0       1  female  38.0      1      0  71.2833        C
2       1.0       3  female  26.0      0      0   7.9250        S
3       1.0       1  female  35.0      1      0  53.1000        S
4       0.0       3    male  35.0      0      0   8.0500        S

In [49]:
titanic_filtrado.shape

(1309, 8)

In [50]:
titanic_filtrado = titanic_filtrado.dropna()
titanic_filtrado.shape

(712, 8)

In [51]:
titanic_filtrado["Embarked"].unique()

array(['S', 'C', 'Q'], dtype=object)

In [52]:
df_modelo = pd.get_dummies(titanic_filtrado, columns=["Sex", "Embarked"], dtype=int)
df_modelo.head()

,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S
0,0.0,3,22.0,1,0,7.2500,0,1,0,0,1
1,1.0,1,38.0,1,0,71.2833,1,0,1,0,0
2,1.0,3,26.0,0,0,7.9250,1,0,0,0,1
3,1.0,1,35.0,1,0,53.1000,1,0,0,0,1
4,0.0,3,35.0,0,0,8.0500,0,1,0,0,1

In [53]:
df_modelo.corr(numeric_only=True)["Survived"].abs().sort_values(ascending=False)[1:]

Sex_male      0.536762
Sex_female    0.536762
Pclass        0.356462
Fare          0.266100
Embarked_C    0.195673
Embarked_S    0.159015
Parch         0.095265
Age           0.082446
Embarked_Q    0.048966
SibSp         0.015523
Name: Survived, dtype: float64

In [54]:
X = df_modelo.drop(['Survived'],axis=1)
y = df_modelo['Survived']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.20, random_state=42, stratify=y
)

In [ ]:
from sklearn.tree import DecisionTreeClassifier

tree_clf = DecisionTreeClassifier(max_depth=2)
tree_clf.fit(X, y)

DecisionTreeClassifier(max_depth=2)

In [56]:
import os

from sklearn.tree import export_graphviz

export_graphviz(
    tree_clf,
    out_file="./titanic_tree.dot",
    feature_names=list(X_train.columns),
    class_names=[str(c) for c in tree_clf.classes_],
    rounded=True,
    filled=True
)

#Usa este comando para transformar la imagen en png y poder verla con el visor de imágenes del SO:
#sudo apt install graphviz
!dot -Tpng titanic_tree.dot -o titanic_tree.png

In [57]:
y_pred = tree_clf.predict(X_test)
print(y_pred)

print("Accuracy: ", accuracy_score(y_test ,y_pred))

[1. 0. 0. 1. 0. 0. 0. 1. 0. 1. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 1. 1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 1. 0. 1. 1. 0. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0.
 1. 1. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 1. 0. 0. 0. 0. 0. 1. 0. 1. 0.
 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 1. 1. 1. 0. 1. 0. 0. 0.]
Accuracy:  0.7902097902097902

In [58]:
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [59]:
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

         0.0       0.75      0.98      0.85        85
         1.0       0.94      0.52      0.67        58

    accuracy                           0.79       143
   macro avg       0.84      0.75      0.76       143
weighted avg       0.82      0.79      0.77       143

In [60]:

valores_C = [0.1, 1, 5, 10, 50, 100]
valores_gamma = [0.001, 0.01, 0.1, 1]
valores_degree = [2, 3, 4, 5]
valores_coef0 = [0, 0.5, 1, 2]

# Funcion que recibe como parametro el tipo de kernel para entrenar el modelo con distintos hiperparametros almacenados en listas
def mejor_eleccion(kernel):
    mejor_acc = 0
    mejor_config = None

    for C in valores_C:

        # LINEAR
        if kernel == 'linear':
            print(f"\nProbando LINEAR | C={C}")

            svm = SVC(kernel='linear', C=C, random_state=42)

            svm.fit(X_train_scaled, y_train)
            pred = svm.predict(X_test_scaled)
            acc = accuracy_score(y_test, pred)

            print(f"Accuracy: {acc:.4f}")

            if acc > mejor_acc:
                mejor_acc = acc
                mejor_config = ('linear', C)

        # RBF
        elif kernel == 'rbf':
            for gamma in valores_gamma:
                print(f"\nProbando RBF | C={C} | gamma={gamma}")

                svm = SVC(kernel='rbf', C=C, gamma=gamma, random_state=42)

                svm.fit(X_train_scaled, y_train)
                pred = svm.predict(X_test_scaled)
                acc = accuracy_score(y_test, pred)

                print(f"Accuracy: {acc:.4f}")

                if acc > mejor_acc:
                    mejor_acc = acc
                    mejor_config = ('rbf', C, gamma)

        # POLY 
        elif kernel == 'poly':
            for degree in valores_degree:
                for coef0 in valores_coef0:
                    print(f"\nProbando POLY | C={C} | degree={degree} | coef0={coef0}")

                    svm = SVC(kernel='poly', C=C, degree=degree, coef0=coef0, random_state=42)

                    svm.fit(X_train_scaled, y_train)
                    pred = svm.predict(X_test_scaled)
                    acc = accuracy_score(y_test, pred)

                    print(f"Accuracy: {acc:.4f}")

                    if acc > mejor_acc:
                        mejor_acc = acc
                        mejor_config = ('poly', C, degree, coef0)

    print(f"\nMejor Accuracy: {mejor_acc:.4f}")
    print(f"Mejor configuración: {mejor_config}")

Poly (C=0.1, degree=3, coef0=2) = 0.8252 
Rbf (C=1, gamma=0.1) = 0.8392
Lineal (C=0.1) = 0.7692

In [61]:
mejor_eleccion("rbf")

Probando RBF | C=0.1 | gamma=0.001
Accuracy: 0.5944

Probando RBF | C=0.1 | gamma=0.01
Accuracy: 0.7832

Probando RBF | C=0.1 | gamma=0.1
Accuracy: 0.7832

Probando RBF | C=0.1 | gamma=1
Accuracy: 0.7483

Probando RBF | C=1 | gamma=0.001
Accuracy: 0.7832

Probando RBF | C=1 | gamma=0.01
Accuracy: 0.7692

Probando RBF | C=1 | gamma=0.1
Accuracy: 0.8392

Probando RBF | C=1 | gamma=1
Accuracy: 0.7832

Probando RBF | C=5 | gamma=0.001
Accuracy: 0.7692

Probando RBF | C=5 | gamma=0.01
Accuracy: 0.7762

Probando RBF | C=5 | gamma=0.1
Accuracy: 0.7832

Probando RBF | C=5 | gamma=1
Accuracy: 0.7832

Probando RBF | C=10 | gamma=0.001
Accuracy: 0.7692

Probando RBF | C=10 | gamma=0.01
Accuracy: 0.8042

Probando RBF | C=10 | gamma=0.1
Accuracy: 0.7902

Probando RBF | C=10 | gamma=1
Accuracy: 0.7622

Probando RBF | C=50 | gamma=0.001
Accuracy: 0.7692

Probando RBF | C=50 | gamma=0.01
Accuracy: 0.8252

Probando RBF | C=50 | gamma=0.1
Accuracy: 0.7622

Probando RBF | C=50 | gamma=1
Accuracy: 0.7622

Probando RBF | C=100 | gamma=0.001
Accuracy: 0.7692

Probando RBF | C=100 | gamma=0.01
Accuracy: 0.8042

Probando RBF | C=100 | gamma=0.1
Accuracy: 0.7552

Probando RBF | C=100 | gamma=1
Accuracy: 0.7552

Mejor Accuracy: 0.8392
Mejor configuración: ('rbf', 1, 0.1)