## Actividad 3_17: Regresión con RN. ¿Cuanto vale un portátil?
<div style="border-style:groove;border-width:thin;padding:10px">
Ya hemos hecho un ejercicio de clasificación con redes neuronales. Vamos a trabajar ahora con uno de regresión. En este caso es un dataset con datos de portátiles. 
</div>

<div style="border-style:groove;border-width:thin;padding:10px">
Debes hacer lo siguiente:
    <ol>
        <li>Carga el archivo "laptop_price.csv".</li>
        <li>Echa un vistazo a los datos. Corrige cosas si es necesario.</li>
        <li>Hay muchas columnas categóricas. Transfórmalas.</li>
        <li>Divide el dataset en conjuntos de training y de test.</li>
        <li>Soluciona el ejercicio con una red neuronal.</li>
    </ol>
</div>

In [2]:
# Datos y preprocesamiento
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
from sklearn.preprocessing import StandardScaler, MinMaxScaler

# Modelos de Clasificación
from sklearn.svm import SVC, LinearSVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier

# Modelos de Regresión
from sklearn.svm import SVR, LinearSVR
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

from tensorflow import keras

# Métricas de Clasificación
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report,
    confusion_matrix
)

# Métricas de Regresión
from sklearn.metrics import (
    mean_squared_error,
    mean_absolute_error,
    r2_score
)

# Visualización
import matplotlib.pyplot as plt
import seaborn as sns

# Configuración
import warnings
warnings.filterwarnings('ignore')
plt.style.use('seaborn-v0_8-darkgrid')

print("Todas las librerías importadas correctamente")

I0000 00:00:1773940108.206016   14521 cpu_feature_guard.cc:227] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1773940117.821408   14521 port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.

Todas las librerías importadas correctamente

In [3]:

df_prices = pd.read_csv('laptop_price.csv', encoding='latin-1')

df_prices.head()

,laptop_ID,Company,Product,TypeName,Inches,ScreenResolution,Cpu,Ram,Memory,Gpu,OpSys,Weight,Price_euros
0,1,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 2.3GHz,8GB,128GB SSD,Intel Iris Plus Graphics 640,macOS,1.37kg,1339.69
1,2,Apple,Macbook Air,Ultrabook,13.3,1440x900,Intel Core i5 1.8GHz,8GB,128GB Flash Storage,Intel HD Graphics 6000,macOS,1.34kg,898.94
2,3,HP,250 G6,Notebook,15.6,Full HD 1920x1080,Intel Core i5 7200U 2.5GHz,8GB,256GB SSD,Intel HD Graphics 620,No OS,1.86kg,575.00
3,4,Apple,MacBook Pro,Ultrabook,15.4,IPS Panel Retina Display 2880x1800,Intel Core i7 2.7GHz,16GB,512GB SSD,AMD Radeon Pro 455,macOS,1.83kg,2537.45
4,5,Apple,MacBook Pro,Ultrabook,13.3,IPS Panel Retina Display 2560x1600,Intel Core i5 3.1GHz,8GB,256GB SSD,Intel Iris Plus Graphics 650,macOS,1.37kg,1803.60

In [4]:
df_prices.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1303 entries, 0 to 1302
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   laptop_ID         1303 non-null   int64
 1   Company           1303 non-null   object
 2   Product           1303 non-null   object
 3   TypeName          1303 non-null   object
 4   Inches            1303 non-null   float64
 5   ScreenResolution  1303 non-null   object
 6   Cpu               1303 non-null   object
 7   Ram               1303 non-null   object
 8   Memory            1303 non-null   object
 9   Gpu               1303 non-null   object
 10  OpSys             1303 non-null   object
 11  Weight            1303 non-null   object
 12  Price_euros       1303 non-null   float64
dtypes: float64(2), int64(1), object(10)
memory usage: 132.5+ KB

In [5]:
def see_columns_unique_values(df, columns):
    for column in columns:
        print(f"Columna: {column}")
        print(len(df[column].unique()))

see_columns_unique_values(df_prices, df_prices.columns)

Columna: laptop_ID
1303
Columna: Company
19
Columna: Product
618
Columna: TypeName
6
Columna: Inches
18
Columna: ScreenResolution
40
Columna: Cpu
118
Columna: Ram
9
Columna: Memory
39
Columna: Gpu
110
Columna: OpSys
9
Columna: Weight
179
Columna: Price_euros
791

In [6]:
df_prices['Gpu'].unique()
df_prices.columns

Index(['laptop_ID', 'Company', 'Product', 'TypeName', 'Inches',
       'ScreenResolution', 'Cpu', 'Ram', 'Memory', 'Gpu', 'OpSys', 'Weight',
       'Price_euros'],
      dtype='object')

In [7]:
df_prices.drop(columns=['laptop_ID', 'Product'], inplace=True)

In [8]:
for index, value in df_prices['Weight'].items():
    df_prices.at[index, 'Weight'] = float(value.replace('kg', '').strip())

In [9]:
for index, value in df_prices['Ram'].items():
    df_prices.at[index, 'Ram'] = int(value.replace('GB', '').strip())

In [10]:
df_prices['Ram'] = df_prices['Ram'].astype(int)
df_prices['Weight'] = df_prices['Weight'].astype(float)

In [11]:
df_prices.corr(numeric_only=True)['Price_euros'].abs().sort_values(ascending=False)[1:]

Ram       0.743007
Weight    0.210370
Inches    0.068197
Name: Price_euros, dtype: float64

In [12]:
df_prices = pd.get_dummies(df_prices, dtype=int)

In [13]:
df_prices.head()

,Inches,Ram,Weight,Price_euros,Company_Acer,Company_Apple,Company_Asus,Company_Chuwi,Company_Dell,Company_Fujitsu,...,Gpu_Nvidia Quadro M620M,OpSys_Android,OpSys_Chrome OS,OpSys_Linux,OpSys_Mac OS X,OpSys_No OS,OpSys_Windows 10,OpSys_Windows 10 S,OpSys_Windows 7,OpSys_macOS
0,13.3,8,1.37,1339.69,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
1,13.3,8,1.34,898.94,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,15.6,8,1.86,575.00,0,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,15.4,16,1.83,2537.45,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
4,13.3,8,1.37,1803.60,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1

In [14]:
X = df_prices.drop(columns=['Price_euros'])
y = df_prices['Price_euros']

scaler = StandardScaler()
X = scaler.fit_transform(X)

In [15]:
X_train_full, X_test, y_train_full, y_test = train_test_split(
X, y, test_size=0.1, random_state=0)

X_train, X_valid, y_train, y_valid = train_test_split(
X_train_full, y_train_full, test_size=0.1, random_state=0)

In [16]:
model = keras.models.Sequential([
keras.layers.Dense(210, activation="relu", input_shape=X_train.shape[1:]),
keras.layers.Dense(140, activation="relu"),
keras.layers.Dense(1)
])

model.compile(loss="mean_absolute_error", optimizer="sgd",metrics=['mae'])

W0000 00:00:1773940124.879268   14521 gpu_device.cc:2365] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
Skipping registering GPU devices...

In [17]:
history = model.fit(X_train, y_train, epochs=300,
validation_data=(X_valid, y_valid))

mse_test = model.evaluate(X_test, y_test)

Epoch 1/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1081.9449 - mae: 1081.9449 - val_loss: 1043.4652 - val_mae: 1043.4652
Epoch 2/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 535.2737 - mae: 535.2737 - val_loss: 289.4411 - val_mae: 289.4411
Epoch 3/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 266.8220 - mae: 266.8220 - val_loss: 222.2318 - val_mae: 222.2318
Epoch 4/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 217.8947 - mae: 217.8947 - val_loss: 276.3011 - val_mae: 276.3011
Epoch 5/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 198.7441 - mae: 198.7441 - val_loss: 235.5614 - val_mae: 235.5614
Epoch 6/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 181.3031 - mae: 181.3031 - val_loss: 254.2830 - val_mae: 254.2830
Epoch 7/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 181.9552 - mae: 181.9552 - val_loss: 216.5304 - val_mae: 216.5304
Epoch 8/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 192.3653 - mae: 192.3653 - val_loss: 218.7263 - val_mae: 218.7263
Epoch 9/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 179.3725 - mae: 179.3725 - val_loss: 256.6007 - val_mae: 256.6007
Epoch 10/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 176.6158 - mae: 176.6158 - val_loss: 260.7134 - val_mae: 260.7134
Epoch 11/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 196.7807 - mae: 196.7807 - val_loss: 287.9776 - val_mae: 287.9776
Epoch 12/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 181.4118 - mae: 181.4118 - val_loss: 264.7429 - val_mae: 264.7429
Epoch 13/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 169.4114 - mae: 169.4114 - val_loss: 205.4581 - val_mae: 205.4581
Epoch 14/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 167.0164 - mae: 167.0164 - val_loss: 215.9377 - val_mae: 215.9377
Epoch 15/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 189.1513 - mae: 189.1513 - val_loss: 240.5191 - val_mae: 240.5191
Epoch 16/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 193.9896 - mae: 193.9896 - val_loss: 221.1869 - val_mae: 221.1869
Epoch 17/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 186.0560 - mae: 186.0560 - val_loss: 233.0483 - val_mae: 233.0483
Epoch 18/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 183.4275 - mae: 183.4275 - val_loss: 252.3938 - val_mae: 252.3938
Epoch 19/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 185.4392 - mae: 185.4392 - val_loss: 209.9394 - val_mae: 209.9394
Epoch 20/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 185.4359 - mae: 185.4359 - val_loss: 225.2072 - val_mae: 225.2072
Epoch 21/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 158.8648 - mae: 158.8648 - val_loss: 212.1232 - val_mae: 212.1232
Epoch 22/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 173.2535 - mae: 173.2535 - val_loss: 238.3260 - val_mae: 238.3260
Epoch 23/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 188.4621 - mae: 188.4621 - val_loss: 314.4569 - val_mae: 314.4569
Epoch 24/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 170.6062 - mae: 170.6062 - val_loss: 241.3008 - val_mae: 241.3008
Epoch 25/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 170.6945 - mae: 170.6945 - val_loss: 339.9687 - val_mae: 339.9687
Epoch 26/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 182.6740 - mae: 182.6740 - val_loss: 273.3997 - val_mae: 273.3997
Epoch 27/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 176.0597 - mae: 176.0597 - val_loss: 243.3429 - val_mae: 243.3429
Epoch 28/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 197.0279 - mae: 197.0279 - val_loss: 242.0070 - val_mae: 242.0070
Epoch 29/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 176.7578 - mae: 176.7578 - val_loss: 202.8588 - val_mae: 202.8588
Epoch 30/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 188.2030 - mae: 188.2030 - val_loss: 307.6767 - val_mae: 307.6767
Epoch 31/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 180.0806 - mae: 180.0806 - val_loss: 242.5354 - val_mae: 242.5354
Epoch 32/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 197.4110 - mae: 197.4110 - val_loss: 213.4332 - val_mae: 213.4332
Epoch 33/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 170.5271 - mae: 170.5271 - val_loss: 223.5312 - val_mae: 223.5313
Epoch 34/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 178.5079 - mae: 178.5079 - val_loss: 297.2819 - val_mae: 297.2819
Epoch 35/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 192.3298 - mae: 192.3298 - val_loss: 362.0720 - val_mae: 362.0720
Epoch 36/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 198.6502 - mae: 198.6502 - val_loss: 274.3636 - val_mae: 274.3636
Epoch 37/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 188.9567 - mae: 188.9567 - val_loss: 279.5683 - val_mae: 279.5683
Epoch 38/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 175.5576 - mae: 175.5576 - val_loss: 204.1086 - val_mae: 204.1086
Epoch 39/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 181.6134 - mae: 181.6134 - val_loss: 226.8520 - val_mae: 226.8520
Epoch 40/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 190.8315 - mae: 190.8315 - val_loss: 246.3191 - val_mae: 246.3191
Epoch 41/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 177.2342 - mae: 177.2342 - val_loss: 275.5335 - val_mae: 275.5335
Epoch 42/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 184.7204 - mae: 184.7204 - val_loss: 219.0136 - val_mae: 219.0136
Epoch 43/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 170.6214 - mae: 170.6214 - val_loss: 238.5476 - val_mae: 238.5476
Epoch 44/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 177.7638 - mae: 177.7638 - val_loss: 223.1708 - val_mae: 223.1708
Epoch 45/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 168.6396 - mae: 168.6396 - val_loss: 217.4906 - val_mae: 217.4906
Epoch 46/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 167.2270 - mae: 167.2270 - val_loss: 285.7831 - val_mae: 285.7831
Epoch 47/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 192.1831 - mae: 192.1831 - val_loss: 222.6694 - val_mae: 222.6694
Epoch 48/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 194.9977 - mae: 194.9977 - val_loss: 293.9250 - val_mae: 293.9250
Epoch 49/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 176.8353 - mae: 176.8353 - val_loss: 227.6996 - val_mae: 227.6996
Epoch 50/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 184.4921 - mae: 184.4921 - val_loss: 217.0783 - val_mae: 217.0783
Epoch 51/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 181.0258 - mae: 181.0258 - val_loss: 250.8111 - val_mae: 250.8111
Epoch 52/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 194.1931 - mae: 194.1931 - val_loss: 247.7272 - val_mae: 247.7272
Epoch 53/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 179.8484 - mae: 179.8484 - val_loss: 265.3438 - val_mae: 265.3438
Epoch 54/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 197.5820 - mae: 197.5820 - val_loss: 218.1485 - val_mae: 218.1485
Epoch 55/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 164.5552 - mae: 164.5552 - val_loss: 266.8574 - val_mae: 266.8574
Epoch 56/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 161.8072 - mae: 161.8072 - val_loss: 239.9480 - val_mae: 239.9480
Epoch 57/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 180.7300 - mae: 180.7300 - val_loss: 210.5629 - val_mae: 210.5629
Epoch 58/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 181.2492 - mae: 181.2492 - val_loss: 252.3252 - val_mae: 252.3252
Epoch 59/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 168.3419 - mae: 168.3419 - val_loss: 326.9900 - val_mae: 326.9900
Epoch 60/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 174.5882 - mae: 174.5882 - val_loss: 274.3491 - val_mae: 274.3491
Epoch 61/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 176.1503 - mae: 176.1503 - val_loss: 237.3678 - val_mae: 237.3678
Epoch 62/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 170.9787 - mae: 170.9787 - val_loss: 288.0640 - val_mae: 288.0640
Epoch 63/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 170.6203 - mae: 170.6203 - val_loss: 289.7474 - val_mae: 289.7474
Epoch 64/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 173.5528 - mae: 173.5528 - val_loss: 206.6530 - val_mae: 206.6530
Epoch 65/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 164.2508 - mae: 164.2508 - val_loss: 323.1874 - val_mae: 323.1874
Epoch 66/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 173.3698 - mae: 173.3698 - val_loss: 209.2233 - val_mae: 209.2233
Epoch 67/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 175.6447 - mae: 175.6447 - val_loss: 202.7947 - val_mae: 202.7947
Epoch 68/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 155.3516 - mae: 155.3516 - val_loss: 243.8865 - val_mae: 243.8865
Epoch 69/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 169.0974 - mae: 169.0974 - val_loss: 256.5363 - val_mae: 256.5363
Epoch 70/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 177.9472 - mae: 177.9472 - val_loss: 253.6564 - val_mae: 253.6564
Epoch 71/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 174.2281 - mae: 174.2281 - val_loss: 278.8490 - val_mae: 278.8490
Epoch 72/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 157.4171 - mae: 157.4171 - val_loss: 258.3117 - val_mae: 258.3117
Epoch 73/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 170.7224 - mae: 170.7224 - val_loss: 223.4985 - val_mae: 223.4985
Epoch 74/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 173.9336 - mae: 173.9336 - val_loss: 243.8840 - val_mae: 243.8840
Epoch 75/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 164.1329 - mae: 164.1329 - val_loss: 224.2322 - val_mae: 224.2322
Epoch 76/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.5572 - mae: 159.5572 - val_loss: 256.6842 - val_mae: 256.6842
Epoch 77/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 174.7171 - mae: 174.7171 - val_loss: 218.0446 - val_mae: 218.0446
Epoch 78/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 162.5522 - mae: 162.5522 - val_loss: 240.9344 - val_mae: 240.9344
Epoch 79/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 182.3078 - mae: 182.3078 - val_loss: 220.0844 - val_mae: 220.0844
Epoch 80/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 164.4648 - mae: 164.4648 - val_loss: 233.9228 - val_mae: 233.9228
Epoch 81/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 175.2137 - mae: 175.2137 - val_loss: 211.7285 - val_mae: 211.7285
Epoch 82/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 176.6988 - mae: 176.6988 - val_loss: 264.9614 - val_mae: 264.9614
Epoch 83/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 164.9745 - mae: 164.9745 - val_loss: 222.1385 - val_mae: 222.1385
Epoch 84/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 184.9619 - mae: 184.9619 - val_loss: 278.1336 - val_mae: 278.1336
Epoch 85/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 174.3527 - mae: 174.3527 - val_loss: 285.9364 - val_mae: 285.9364
Epoch 86/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 180.1218 - mae: 180.1218 - val_loss: 235.0160 - val_mae: 235.0160
Epoch 87/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 160.4263 - mae: 160.4263 - val_loss: 269.7715 - val_mae: 269.7715
Epoch 88/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 171.9982 - mae: 171.9982 - val_loss: 233.2042 - val_mae: 233.2042
Epoch 89/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 156.3335 - mae: 156.3335 - val_loss: 215.0266 - val_mae: 215.0266
Epoch 90/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 166.1360 - mae: 166.1360 - val_loss: 251.0753 - val_mae: 251.0753
Epoch 91/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 152.1833 - mae: 152.1833 - val_loss: 212.8029 - val_mae: 212.8029
Epoch 92/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 165.4261 - mae: 165.4261 - val_loss: 238.5991 - val_mae: 238.5991
Epoch 93/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 173.2583 - mae: 173.2583 - val_loss: 215.8417 - val_mae: 215.8417
Epoch 94/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 165.8454 - mae: 165.8454 - val_loss: 263.7643 - val_mae: 263.7643
Epoch 95/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 156.1890 - mae: 156.1890 - val_loss: 242.6788 - val_mae: 242.6788
Epoch 96/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 147.2079 - mae: 147.2079 - val_loss: 228.5365 - val_mae: 228.5365
Epoch 97/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 160.3160 - mae: 160.3160 - val_loss: 209.1857 - val_mae: 209.1857
Epoch 98/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.6522 - mae: 159.6522 - val_loss: 233.7471 - val_mae: 233.7471
Epoch 99/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 147.7141 - mae: 147.7141 - val_loss: 218.6641 - val_mae: 218.6641
Epoch 100/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 162.7355 - mae: 162.7355 - val_loss: 214.0940 - val_mae: 214.0940
Epoch 101/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 162.2843 - mae: 162.2843 - val_loss: 215.9410 - val_mae: 215.9410
Epoch 102/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.4324 - mae: 163.4324 - val_loss: 210.4325 - val_mae: 210.4325
Epoch 103/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 164.4357 - mae: 164.4357 - val_loss: 231.3958 - val_mae: 231.3958
Epoch 104/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 160.1926 - mae: 160.1926 - val_loss: 214.6185 - val_mae: 214.6185
Epoch 105/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 144.5115 - mae: 144.5115 - val_loss: 263.1261 - val_mae: 263.1261
Epoch 106/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 167.0914 - mae: 167.0914 - val_loss: 192.7361 - val_mae: 192.7361
Epoch 107/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 167.5227 - mae: 167.5227 - val_loss: 265.9958 - val_mae: 265.9958
Epoch 108/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 159.7169 - mae: 159.7169 - val_loss: 235.7200 - val_mae: 235.7200
Epoch 109/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 173.0437 - mae: 173.0437 - val_loss: 224.3324 - val_mae: 224.3324
Epoch 110/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 151.5458 - mae: 151.5458 - val_loss: 199.6916 - val_mae: 199.6916
Epoch 111/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 136.3964 - mae: 136.3964 - val_loss: 238.4157 - val_mae: 238.4157
Epoch 112/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 158.6965 - mae: 158.6965 - val_loss: 264.7508 - val_mae: 264.7508
Epoch 113/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.3635 - mae: 159.3635 - val_loss: 298.8581 - val_mae: 298.8581
Epoch 114/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 149.6743 - mae: 149.6743 - val_loss: 221.2810 - val_mae: 221.2810
Epoch 115/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 158.7500 - mae: 158.7500 - val_loss: 214.1108 - val_mae: 214.1108
Epoch 116/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.0842 - mae: 163.0842 - val_loss: 258.5294 - val_mae: 258.5294
Epoch 117/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 171.4236 - mae: 171.4236 - val_loss: 236.0394 - val_mae: 236.0394
Epoch 118/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 155.3890 - mae: 155.3890 - val_loss: 221.8624 - val_mae: 221.8624
Epoch 119/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 152.3339 - mae: 152.3339 - val_loss: 243.9636 - val_mae: 243.9636
Epoch 120/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 161.8382 - mae: 161.8382 - val_loss: 212.6544 - val_mae: 212.6544
Epoch 121/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 127.0790 - mae: 127.0790 - val_loss: 229.1469 - val_mae: 229.1469
Epoch 122/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 170.1448 - mae: 170.1448 - val_loss: 255.2480 - val_mae: 255.2480
Epoch 123/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 161.0449 - mae: 161.0449 - val_loss: 255.1505 - val_mae: 255.1505
Epoch 124/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 162.8292 - mae: 162.8292 - val_loss: 218.3787 - val_mae: 218.3787
Epoch 125/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 161.5645 - mae: 161.5645 - val_loss: 231.4986 - val_mae: 231.4986
Epoch 126/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 151.5809 - mae: 151.5809 - val_loss: 262.7949 - val_mae: 262.7949
Epoch 127/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 155.1418 - mae: 155.1418 - val_loss: 210.0134 - val_mae: 210.0134
Epoch 128/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 148.3209 - mae: 148.3209 - val_loss: 233.6767 - val_mae: 233.6767
Epoch 129/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.2271 - mae: 163.2271 - val_loss: 256.6364 - val_mae: 256.6364
Epoch 130/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 149.8185 - mae: 149.8185 - val_loss: 232.1534 - val_mae: 232.1534
Epoch 131/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 151.1023 - mae: 151.1023 - val_loss: 247.1842 - val_mae: 247.1842
Epoch 132/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 169.5901 - mae: 169.5901 - val_loss: 205.0895 - val_mae: 205.0895
Epoch 133/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.6471 - mae: 159.6471 - val_loss: 260.5740 - val_mae: 260.5740
Epoch 134/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 160.8925 - mae: 160.8925 - val_loss: 239.0526 - val_mae: 239.0526
Epoch 135/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 166.7362 - mae: 166.7362 - val_loss: 227.9943 - val_mae: 227.9943
Epoch 136/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 163.3943 - mae: 163.3943 - val_loss: 231.2783 - val_mae: 231.2783
Epoch 137/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 161.0415 - mae: 161.0415 - val_loss: 209.5678 - val_mae: 209.5678
Epoch 138/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 148.5379 - mae: 148.5379 - val_loss: 203.4517 - val_mae: 203.4517
Epoch 139/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 126.7619 - mae: 126.7619 - val_loss: 208.7286 - val_mae: 208.7286
Epoch 140/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 134.2994 - mae: 134.2994 - val_loss: 222.7302 - val_mae: 222.7302
Epoch 141/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 150.6066 - mae: 150.6066 - val_loss: 238.3442 - val_mae: 238.3442
Epoch 142/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 152.8941 - mae: 152.8941 - val_loss: 209.4898 - val_mae: 209.4898
Epoch 143/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 149.5359 - mae: 149.5359 - val_loss: 212.6278 - val_mae: 212.6278
Epoch 144/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 146.1021 - mae: 146.1021 - val_loss: 214.5088 - val_mae: 214.5088
Epoch 145/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 120.4442 - mae: 120.4442 - val_loss: 285.4287 - val_mae: 285.4287
Epoch 146/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 151.0875 - mae: 151.0875 - val_loss: 245.7757 - val_mae: 245.7757
Epoch 147/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 159.8045 - mae: 159.8045 - val_loss: 225.4730 - val_mae: 225.4730
Epoch 148/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 142.1429 - mae: 142.1429 - val_loss: 244.1809 - val_mae: 244.1809
Epoch 149/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 148.5441 - mae: 148.5441 - val_loss: 209.7292 - val_mae: 209.7292
Epoch 150/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 132.3465 - mae: 132.3465 - val_loss: 226.3408 - val_mae: 226.3408
Epoch 151/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 139.9332 - mae: 139.9332 - val_loss: 257.3617 - val_mae: 257.3617
Epoch 152/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 146.1745 - mae: 146.1745 - val_loss: 217.1865 - val_mae: 217.1865
Epoch 153/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 139.1938 - mae: 139.1938 - val_loss: 285.5067 - val_mae: 285.5067
Epoch 154/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 147.6543 - mae: 147.6543 - val_loss: 213.3317 - val_mae: 213.3317
Epoch 155/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 152.3907 - mae: 152.3907 - val_loss: 219.0442 - val_mae: 219.0442
Epoch 156/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 154.5570 - mae: 154.5570 - val_loss: 238.3959 - val_mae: 238.3959
Epoch 157/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 152.1382 - mae: 152.1382 - val_loss: 216.1381 - val_mae: 216.1381
Epoch 158/300
33/33 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 160.5711 - mae: 160.5711 - val_loss: 192.9357 - val_mae: 192.9357
Epoch 159/300

In [18]:
X_new = X_test[:3] 
y_pred = model.predict(X_new)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

In [19]:
y_pred = model.predict(X_test)
r2_score(y_test, y_pred)

5/5 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

0.7918798186353019

In [20]:
model.save("price_predictor.keras")