In [35]:
import numpy as np
import matplotlib.pyplot as plt

from sklearn.datasets import make_circles
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [1]:
import pandas as pd

adult = pd.read_csv("adult.csv")
adult.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,<=50K
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,<=50K
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,<=50K
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,<=50K
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,<=50K

In [3]:
df_filtrado = adult.copy()

df_filtrado["income"].replace({
    ">50K": 1,
    "<=50K": 0
}, inplace=True)

/tmp/ipykernel_26419/3112973389.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_filtrado["income"].replace({
/tmp/ipykernel_26419/3112973389.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df_filtrado["income"].replace({

In [4]:
df_filtrado.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,0
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,0
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,0
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,0
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,0

In [16]:
df_filtrado["income"] = df_filtrado["income"].astype(int)

In [18]:
df_filtrado.head()

,age,workclass,fnlwgt,education,education.num,marital.status,occupation,relationship,race,sex,capital.gain,capital.loss,hours.per.week,native.country,income
0,90,?,77053,HS-grad,9,Widowed,?,Not-in-family,White,Female,0,4356,40,United-States,0
1,82,Private,132870,HS-grad,9,Widowed,Exec-managerial,Not-in-family,White,Female,0,4356,18,United-States,0
2,66,?,186061,Some-college,10,Widowed,?,Unmarried,Black,Female,0,4356,40,United-States,0
3,54,Private,140359,7th-8th,4,Divorced,Machine-op-inspct,Unmarried,White,Female,0,3900,40,United-States,0
4,41,Private,264663,Some-college,10,Separated,Prof-specialty,Own-child,White,Female,0,3900,40,United-States,0

In [24]:
cat_cols = df_filtrado.select_dtypes(include="object").columns.tolist()
print(cat_cols)

['workclass', 'education', 'marital.status', 'occupation', 'relationship', 'race', 'sex', 'native.country']

In [25]:
columnas = cat_cols
print(type(columnas))

<class 'list'>

In [27]:
df_final = df_filtrado.drop(columns=cat_cols)
df_final.head()

,age,fnlwgt,education.num,capital.gain,capital.loss,hours.per.week,income
0,90,77053,9,0,4356,40,0
1,82,132870,9,0,4356,18,0
2,66,186061,10,0,4356,40,0
3,54,140359,4,0,3900,40,0
4,41,264663,10,0,3900,40,0

In [28]:
X = df_final.drop(columns="income")
y = df_final["income"]

print(X.shape)
print(y.shape)

(32561, 6)
(32561,)

In [29]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=16, stratify=y
)

In [30]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [31]:
from sklearn.svm import SVC

svm_lineal = SVC(kernel="linear", C=1.0, random_state=42)
svm_lineal.fit(X_train_scaled, y_train)

SVC(kernel='linear', random_state=42)

In [ ]:
svm_rbf = SVC(kernel="rbf", C=1.0, gamma=1.0, random_state=42)
svm_rbf.fit(X_train_scaled, y_train)

SVC(C=5.0, gamma=2.0, random_state=42)

In [ ]:
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

pred_lineal = svm_lineal.predict(X_test_scaled)
pred_rbf = svm_rbf.predict(X_test_scaled)

print("=== SVM LINEAL ===")
print("Accuracy:", accuracy_score(y_test, pred_lineal)) 
print(confusion_matrix(y_test, pred_lineal))
print(classification_report(y_test, pred_lineal))

print("\n=== SVM RBF ===")
print("Accuracy:", accuracy_score(y_test, pred_rbf))
print(confusion_matrix(y_test, pred_rbf))
print(classification_report(y_test, pred_rbf))

=== SVM LINEAL ===
Accuracy: 0.800761577201818
[[5925  256]
 [1366  594]]
              precision    recall  f1-score   support

           0       0.81      0.96      0.88      6181
           1       0.70      0.30      0.42      1960

    accuracy                           0.80      8141
   macro avg       0.76      0.63      0.65      8141
weighted avg       0.79      0.80      0.77      8141


=== SVM RBF ===
Accuracy: 0.8193096671170618
[[5854  327]
 [1144  816]]
              precision    recall  f1-score   support

           0       0.84      0.95      0.89      6181
           1       0.71      0.42      0.53      1960

    accuracy                           0.82      8141
   macro avg       0.78      0.68      0.71      8141
weighted avg       0.81      0.82      0.80      8141

In [38]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

valores_C = [0.1, 1, 5, 10, 50, 100]
valores_gamma = [0.001, 0.01, 0.1, 1]

mejor_acc = 0
mejor_config = None

# Bucle para probar varias combinaciones de C y gamma para comprobar cual da el mejor accuracy
for C in valores_C:
    for gamma in valores_gamma:
        print(f"\nProbando C={C} | gamma={gamma}")
        
        svm_rbf = SVC(kernel="rbf", C=C, gamma=gamma, random_state=42)
        svm_rbf.fit(X_train_scaled, y_train)

        pred = svm_rbf.predict(X_test_scaled)
        acc = accuracy_score(y_test, pred)

        print(f"Accuracy: {acc:.4f}")

        if acc > mejor_acc:
            mejor_acc = acc
            mejor_config = (C, gamma)

Probando C=0.1 | gamma=0.001
Accuracy: 0.7645

Probando C=0.1 | gamma=0.01
Accuracy: 0.8063

Probando C=0.1 | gamma=0.1
Accuracy: 0.8202

Probando C=0.1 | gamma=1
Accuracy: 0.8183

Probando C=1 | gamma=0.001
Accuracy: 0.8028

Probando C=1 | gamma=0.01
Accuracy: 0.8116

Probando C=1 | gamma=0.1
Accuracy: 0.8247

Probando C=1 | gamma=1
Accuracy: 0.8280

Probando C=5 | gamma=0.001
Accuracy: 0.8116

Probando C=5 | gamma=0.01
Accuracy: 0.8139

Probando C=5 | gamma=0.1
Accuracy: 0.8256

Probando C=5 | gamma=1
Accuracy: 0.8259

Probando C=10 | gamma=0.001
Accuracy: 0.8118

Probando C=10 | gamma=0.01
Accuracy: 0.8154

Probando C=10 | gamma=0.1
Accuracy: 0.8267

Probando C=10 | gamma=1
Accuracy: 0.8248

Probando C=50 | gamma=0.001
Accuracy: 0.8113

Probando C=50 | gamma=0.01
Accuracy: 0.8175

Probando C=50 | gamma=0.1
Accuracy: 0.8272

Probando C=50 | gamma=1
Accuracy: 0.8204

Probando C=100 | gamma=0.001
Accuracy: 0.8111

Probando C=100 | gamma=0.01
Accuracy: 0.8189

Probando C=100 | gamma=0.1
Accuracy: 0.8261

Probando C=100 | gamma=1
Accuracy: 0.8154

In [39]:
print(f"Mejor Accuracy: {mejor_acc:.4f}")
print(f"Mejor C y gamma: C={mejor_config[0]}, gamma={mejor_config[1]}")

Mejor Accuracy: 0.8280
Mejor C y gamma: C=1, gamma=1